# Site settings
title: SIGNAL Lab
name: SIGNAL Lab
description: Situated Grounding and Natural Language <br/> NLP @ CSU
cover: assets/images/bg.png
titleimg: assets/images/signal-cat.png
logo: assets/images/logo.png
favicon: assets/images/logo.png
footerimg: assets/images/csu.png
baseurl: "https://www.signallab.ai/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://www.signallab.ai/" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
github: csu-signal

#Additional Pages
about: about
contact: contact
mission-statement: mission-statement


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: csu-signal #github username
repo: web #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://csu-signal.github.io/web
source_url:  https://github.com/csu-signal/web #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
